baseURL = "https://turing-machines.github.io"
languageCode = "en-us"
title = "Turing Machines Documentation"
# theme = "hugo-future-imperfect"
theme = "hugo-theme-learn"
preserveTaxonomyNames = true
paginate = 10
disqusShortname = "turingpi"
# googleAnalytics = "UA-123357787-2" # Enable Google Analytics by entering your tracking id
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Turing Machines Team"
  # Description of the site, will be used in meta information
  description = "Turing Machines Documentation" # Description of your site
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "kubedge"

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/post/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  identifier = "fa fa-list"
  weight = 4

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 5

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github           = "turing-machines"
  # gitlab           = ""
  # stackoverflow    = "" # User Number
  # bitbucket        = ""
  # jsfiddle         = ""
  # codepen          = ""
  # Visual Art Communities
  # deviantart       = ""
  # flickr           = "example"
  # behance          = ""
  # dribbble         = ""
  # Publishing Communities
  wordpress        = ""
  medium           = ""
  # Professional/Business Oriented Communities
  linkedin         = ""
  # linkedin_company = "examplebusiness"
  # foursquare       = ""
  # xing             = ""
  # slideshare       = ""
  # Social Networks
  # facebook         = "example"
  # googleplus       = ""
  # reddit           = "example"
  # quora            = ""
  # youtube          = ""
  # vimeo            = ""
  # whatsapp         = "" # WhatsApp Number
  # WeChat and QQ need testing.
  # wechat         = ""
  # qq             = "" # User ID Number
  # instagram        = "example"
  # tumblr           = ""
  twitter          = "turingpi"
  # skype            = ""
  # snapchat         = ""
  # pinterest        = "example"
  # telegram         = "example"
  # vine             = ""
  # googlescholar    = ""
  # orcid            = ""
  # researchgate     = "example"
  # Email
  email            = "ask@turingpi.com"
